name: Publish to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          preferLatestVersion: 'true'
          
      - name: Determine Version          
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish and push the container image
        run: |
          dotnet publish --os linux --arch x64 -c Release /t:PublishContainer -p ContainerRegistry=ghcr.io 