on:
  push:
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x      
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish container to GHCR
      run: |
        dotnet publish \
        --os linux \
        --arch x64 \
        -p ContainerImageTags='"latest"' \
        -p ContainerRegistry=ghcr.io \
        -t:PublishContainer