name: Publish to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container to GHCR
        run: |
          dotnet publish \
          --os linux \
          --arch x64 \
          -p ContainerImageTags='"latest;"' \
          -p ContainerRegistry=ghcr.io \
          -p ContainerRepository=${{ github.repository }} \
          -t:PublishContainer